export const GET_PROVINCE_LIST = 'GET_PROVINCE_LIST';
export const GET_LOCATION_LIST = 'GET_LOCATION_LIST';
export const GET_SERVICE_LIST = 'GET_SERVICE_LIST';
export const LOADING_PROVINCES = 'LOADING_PROVINCES';
export const LOADING_LOCATIONS = 'LOADING_LOCATIONS';
export const LOADING_SERVICES = 'LOADING_SERVICES';
export const PROVINCE_PAGE = 'PROVINCE_PAGE';
export const PROVINCE_ERROR = 'PROVINCE_ERROR';
